[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "django_scripture_index"
author = "Nathan Patton"
author-email = "npatton@gmail.com"
home-page = "https://github.com/avendesora/django-scripture-index"
classifiers = ["License :: OSI Approved :: MIT License"]
description-file = "README.md"
requires-python=">=3.6"
requires = [
    "Django>=3.1.1"
]

[tool.flit.metadata.requires-extra]
test = [
    "pytest>=6.0.2",
    "pytest-cov>=2.10.1",
]

